CREATE OR REPLACE DATABASE OPENBIOOPS;
USE DATABASE OPENBIOOPS;
CREATE OR REPLACE SCHEMA PUBLIC;
CREATE OR REPLACE TABLE FEATURES (
  sample_id STRING,
  cell_id STRING,
  gene_counts VARIANT,
  embedding ARRAY
);